### ISSUE TITLE
Iptable Infrastructrue's update method will cause data lose

### ISSUE THREAD

**Issue by ji03mmy18** [YunNet-bot/YunNet-Backend#13]
## Type

- [x] Critical issue report
- [ ] Minor issue report

## How to produce
```typescript=
IptableInfra.getInstance().update('140.125.202.202', undefined, undefined, undefined, undefined, undefined, 'ABCDEF012345', undefined, undefined, undefined, undefined);
```
This will cause the data with PK = '140.125.202.202' 'all the columns become undefined except mac address.

## Description
When user or frontend send a update request with part of the parameters, the part that not given will become Undefined.

## Possible solution
Use findOne method to search the object and update the detail rather than create and replace it.

**Comment by Iittlefish** [comment]
in my testing, i found that if pk is specified. typeorm will ignore those undefined properties. The updated data  will not be corrupted.
